name: CI/CD Workflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

env:
  WORKING_DIRECTORY: SchedulifySystem.API

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}

      - name: Build
        run: dotnet build ${{ env.WORKING_DIRECTORY }} --no-restore

      - name: Test
        run: dotnet test ${{ env.WORKING_DIRECTORY }} --no-build --verbosity normal

  deploy-backend:
    runs-on: self-hosted

    needs: build  # Đảm bảo deploy chỉ chạy sau khi build thành công

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and deploy with Docker Compose
        run: docker compose -f docker-compose.yml up --build -d
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
