name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  WORKING_DIRECTORY: SchedulifySystem.API
  SOLUTION_FILE: SchedulifySystem.API.sln

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.WORKING_DIRECTORY }}/${{ env.SOLUTION_FILE }}

    - name: Build
      run: dotnet build ${{ env.WORKING_DIRECTORY }}/${{ env.SOLUTION_FILE }} --no-restore

    - name: Test
      run: dotnet test ${{ env.WORKING_DIRECTORY }}/${{ env.SOLUTION_FILE }} --no-build --verbosity normal
